# Generated by Django 5.2 on 2025-04-08 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'TODO'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'HIGH'), ('low', 'LOW'), ('medium', 'MEDIUM')], default='low', max_length=20)),
                ('duedate', models.DateField()),
                ('created_at', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_task_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
